apiVersion: v1
kind: Service
metadata:
  name: projectxx-svc
spec:
  type: NodePort
  selector:
    app: projectxx
  ports:
    - name: http
      nodePort: 30080 
      port: 1234
      targetPort: 3000