import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TodoCreator from './components/todoCreator'
import TodoList from './components/todoList'

export default function Home() {
  const todos = [
    {id: 1, text: 'TODO 1'},
    {id: 2, text: 'TODO 2'}
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{width: '100%', 'align-items': 'flex-start'}}>
        <Image alt="Muk" src="/api/image" width="350" height="200" />
        <TodoCreator />
        <TodoList todos={todos}/>
      </main>
    </div>
  )
}
