apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput
          image: jc40/logoutput:1.0.0