apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-writer-reader
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000