apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-writer-reader-hpa
  namespace: pingpong-writer-reader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-writer-reader
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50